name: forcebundle
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - anyio=2.1.0
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.38.0
  - atk-1.0=2.36.0
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - beautifulsoup4=4.9.3
  - black=20.8b1
  - bleach=3.3.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bs4=4.9.3
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - cairomm=1.12.2
  - cairomm-1.0=1.12.2
  - certifi=2020.12.5
  - cffi=1.14.5
  - cfgv=3.2.0
  - cfitsio=3.470
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - colorama=0.4.4
  - colormath=3.0.0
  - configparser=5.0.1
  - coverage=5.4
  - cryptography=3.4.4
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dataclasses=0.7
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - distlib=0.3.1
  - docutils=0.16
  - editdistance=0.5.3
  - entrypoints=0.3
  - epoxy=1.5.5
  - expat=2.2.10
  - filelock=3.0.12
  - fiona=1.8.18
  - flake8=3.8.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.5
  - fribidi=1.0.10
  - gdal=3.1.4
  - gdk-pixbuf=2.42.2
  - geopandas=0.8.2
  - geos=3.9.0
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.7
  - glib-tools=2.66.7
  - gmp=6.2.1
  - gobject-introspection=1.66.1
  - graph-tool=2.37
  - graphite2=1.3.13
  - graphviz=2.46.1
  - gst-plugins-base=1.18.3
  - gstreamer=1.18.3
  - gtk2=2.24.33
  - gtk3=3.24.24
  - gts=0.7.6
  - harfbuzz=2.7.4
  - hdf4=4.2.13
  - hdf5=1.10.6
  - hicolor-icon-theme=0.17
  - icu=68.1
  - identify=1.5.14
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - iniconfig=1.1.1
  - ipykernel=5.5.0
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - isort=5.7.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9d
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.11
  - jupyter_core=4.7.1
  - jupyter_server=1.4.0
  - jupyterlab=3.0.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.3.0
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.1
  - libcurl=7.71.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgd=2.3.0
  - libgdal=3.1.4
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.7
  - libgomp=9.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.0.1
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=13.1
  - libpysal=4.4.0
  - librsvg=2.50.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - llvmlite=0.35.0
  - lz4-c=1.9.3
  - mapclassify=2.4.2
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - mistune=0.8.4
  - more-itertools=8.7.0
  - munch=2.5.0
  - mypy=0.812
  - mypy_extensions=0.4.3
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - nb_black=1.0.7
  - nbclassic=0.2.6
  - nbclient=0.5.2
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - networkx=2.5
  - nodeenv=1.5.0
  - notebook=6.2.0
  - nspr=4.29
  - nss=3.62
  - numba=0.52.0
  - numpy=1.20.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.2
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.8.1
  - pathspec=0.8.1
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0.1
  - pixman=0.40.0
  - pluggy=0.13.1
  - pockets=0.9.1
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=13.1
  - pre-commit=2.10.1
  - proj=7.2.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.16
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.10.0
  - pycairo=1.20.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pyflakes=2.2.0
  - pygments=2.8.0
  - pygobject=3.38.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=3.0.0.post1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.2.2
  - pytest-cov=2.11.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - readline=8.0
  - regex=2020.11.13
  - requests=2.25.1
  - rtree=0.9.7
  - scikit-learn=0.24.1
  - scipy=1.6.0
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - sigcpp-2.0=2.10.3
  - six=1.15.0
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - soupsieve=2.0.1
  - sparsehash=2.0.3
  - spectra=0.0.11
  - sphinx=3.5.1
  - sphinx-automodapi=0.13
  - sphinx_rtd_theme=0.5.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-napoleon=0.7
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.34.0
  - statsmodels=0.12.2
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tiledb=2.2.4
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.57.0
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - tzcode=2021a
  - urllib3=1.26.3
  - virtualenv=20.4.2
  - watermark=2.2.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - wordcloud=1.8.1
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.4.0
  - zlib=1.2.11
  - zstandard=0.15.1
  - zstd=1.4.8
  - pip:
    - adjusttext==0.7.3
    - flashtext==2.7
    - forcebundle==0.0.1
    - kdepy==1.0.10
    - mock==4.0.3
    - scattertext==0.1.0.0
